#[derive(Debug, Clone, Copy)]
pub(crate) struct EpisodeSpec {
    pub provider: &'static str,
    pub id: &'static str,
    pub category: &'static str,
    pub table: &'static str,
    pub telemetry_file: &'static str,
    pub malicious: bool,
    pub scenario: Scenario,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum Scenario {
    Legacy,
    Benign,
    MultiStage,
    CrossBoundary,
}

pub(crate) const EPISODES: [EpisodeSpec; 18] = [
    EpisodeSpec {
        provider: "aws",
        id: "aws-iam-001",
        category: "identity_compromise",
        table: "aws_cloudtrail",
        telemetry_file: "cloudtrail.parquet",
        malicious: true,
        scenario: Scenario::Legacy,
    },
    EpisodeSpec {
        provider: "aws",
        id: "aws-iam-002",
        category: "privilege_escalation",
        table: "aws_cloudtrail",
        telemetry_file: "cloudtrail.parquet",
        malicious: true,
        scenario: Scenario::Legacy,
    },
    EpisodeSpec {
        provider: "aws",
        id: "aws-iam-003",
        category: "persistence_credential_creation",
        table: "aws_cloudtrail",
        telemetry_file: "cloudtrail.parquet",
        malicious: true,
        scenario: Scenario::Legacy,
    },
    EpisodeSpec {
        provider: "aws",
        id: "aws-iam-004",
        category: "identity_activity_review",
        table: "aws_cloudtrail",
        telemetry_file: "cloudtrail.parquet",
        malicious: false,
        scenario: Scenario::Benign,
    },
    EpisodeSpec {
        provider: "aws",
        id: "aws-iam-005",
        category: "multi_stage_identity_attack",
        table: "aws_cloudtrail",
        telemetry_file: "cloudtrail.parquet",
        malicious: true,
        scenario: Scenario::MultiStage,
    },
    EpisodeSpec {
        provider: "aws",
        id: "aws-iam-006",
        category: "cross_boundary_identity_attack",
        table: "aws_cloudtrail",
        telemetry_file: "cloudtrail.parquet",
        malicious: true,
        scenario: Scenario::CrossBoundary,
    },
    EpisodeSpec {
        provider: "azure",
        id: "azure-iam-001",
        category: "identity_compromise",
        table: "azure_activity",
        telemetry_file: "activity.parquet",
        malicious: true,
        scenario: Scenario::Legacy,
    },
    EpisodeSpec {
        provider: "azure",
        id: "azure-iam-002",
        category: "privilege_escalation",
        table: "azure_activity",
        telemetry_file: "activity.parquet",
        malicious: true,
        scenario: Scenario::Legacy,
    },
    EpisodeSpec {
        provider: "azure",
        id: "azure-iam-003",
        category: "persistence_credential_creation",
        table: "azure_activity",
        telemetry_file: "activity.parquet",
        malicious: true,
        scenario: Scenario::Legacy,
    },
    EpisodeSpec {
        provider: "azure",
        id: "azure-iam-004",
        category: "identity_activity_review",
        table: "azure_activity",
        telemetry_file: "activity.parquet",
        malicious: false,
        scenario: Scenario::Benign,
    },
    EpisodeSpec {
        provider: "azure",
        id: "azure-iam-005",
        category: "multi_stage_identity_attack",
        table: "azure_activity",
        telemetry_file: "activity.parquet",
        malicious: true,
        scenario: Scenario::MultiStage,
    },
    EpisodeSpec {
        provider: "azure",
        id: "azure-iam-006",
        category: "cross_boundary_identity_attack",
        table: "azure_activity",
        telemetry_file: "activity.parquet",
        malicious: true,
        scenario: Scenario::CrossBoundary,
    },
    EpisodeSpec {
        provider: "gcp",
        id: "gcp-iam-001",
        category: "identity_compromise",
        table: "gcp_audit",
        telemetry_file: "audit.parquet",
        malicious: true,
        scenario: Scenario::Legacy,
    },
    EpisodeSpec {
        provider: "gcp",
        id: "gcp-iam-002",
        category: "privilege_escalation",
        table: "gcp_audit",
        telemetry_file: "audit.parquet",
        malicious: true,
        scenario: Scenario::Legacy,
    },
    EpisodeSpec {
        provider: "gcp",
        id: "gcp-iam-003",
        category: "persistence_credential_creation",
        table: "gcp_audit",
        telemetry_file: "audit.parquet",
        malicious: true,
        scenario: Scenario::Legacy,
    },
    EpisodeSpec {
        provider: "gcp",
        id: "gcp-iam-004",
        category: "identity_activity_review",
        table: "gcp_audit",
        telemetry_file: "audit.parquet",
        malicious: false,
        scenario: Scenario::Benign,
    },
    EpisodeSpec {
        provider: "gcp",
        id: "gcp-iam-005",
        category: "multi_stage_identity_attack",
        table: "gcp_audit",
        telemetry_file: "audit.parquet",
        malicious: true,
        scenario: Scenario::MultiStage,
    },
    EpisodeSpec {
        provider: "gcp",
        id: "gcp-iam-006",
        category: "cross_boundary_identity_attack",
        table: "gcp_audit",
        telemetry_file: "audit.parquet",
        malicious: true,
        scenario: Scenario::CrossBoundary,
    },
];
