[package]
name = "hunteval-cli"
description = "Command-line interface for HuntEval"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "hunteval"
path = "src/main.rs"

[dependencies]
clap.workspace = true
hunteval-runner = { path = "../hunteval-runner", version = "0.1.0" }
serde.workspace = true
serde_json.workspace = true

[dev-dependencies]
tempfile = "3.25"

[lints]
workspace = true
