[package]
name = "hunteval-cli"
description = "Command-line interface for HuntEval"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "hunteval"
path = "src/main.rs"

[dependencies]
clap.workspace = true

[lints]
workspace = true
